### ISSUE TITLE
Use of an unnecessary while loop

### ISSUE THREAD

**Issue by LodisAIE** [mikeLofton/BattleArenaExercise#1]
https://github.com/mikeLofton/BattleArenaExercise/blob/1d88fa2bc63b9ac628beb58f92837f62aadff75a/BattleArena/Game.cs#L193-L212

This function is called inside the `Update` function. Which means that it's called every time the game loops. Since, it's already in a loop, a new one is not needed here. You can just keep this scene going, and only change it when the player confirms that they want to keep the name.

**Comment by mikeLofton** [comment]
Removed the loop.
Fixed the code so that the scene progresses.
